/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nanjiang' at '25/03/18 11:45 AM' with Gradle 2.9
 *
 * @author nanjiang, @date 25/03/18 11:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
